import type { Metadata } from "next";
import { Suspense } from "react";
import {
  DatTrackerPrototype,
  type CompanyRecord,
  type ScoreCategory,
} from "../dat-tracker-prototype/tracker-client";

const title = "Digital Asset Treasury Company Tracker™ | DATX";
const description =
  "Independent research, Treasury Quality Scores (TQS), and market intelligence for public digital asset treasury companies.";
const url = "https://datxstrategy.com/tracker";

const tqsFramework = [
  ["Treasury Rationale", 10],
  ["Capital Structure", 10],
  ["Funding & Capital Markets", 10],
  ["Operating Business Strength", 10],
  ["Liquidity & Resilience", 20],
  ["Governance & Risk Controls", 15],
  ["Execution & Transparency", 15],
  ["Shareholder Alignment", 10],
] as const;

function categories(scores: number[]): ScoreCategory[] {
  return tqsFramework.map(([label, max], index) => ({
    label,
    score: scores[index],
    max,
  }));
}

const companies: CompanyRecord[] = [
  {
    slug: "strategy",
    name: "Strategy",
    ticker: "MSTR",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Bitcoin",
    assetLabel: "BTC",
    holdings: "843,775 BTC",
    treasuryNav: "$54.70B",
    treasuryNavValue: 54.7,
    marketCap: "$32.58B",
    marketCapValue: 32.58,
    mnav: "0.60x",
    model: "Levered Bitcoin treasury platform",
    rating: {
      status: "rated",
      score: 84,
      grade: "A",
      confidence: 5,
      lastReviewed: "16 Jul 2026",
      categories: categories([10, 8, 10, 6, 16, 12, 14, 8]),
      analystSummary:
        "Strategy remains the benchmark for capital-market innovation and large-scale Bitcoin treasury execution. Its exceptional access to funding and clear treasury rationale are offset by single-asset concentration, capital-stack complexity, recurring senior claims, and key-person dependence.",
      treasuryModel: "Capital markets-led Bitcoin accumulation",
      strengths: [
        "Clear treasury rationale with long operating history as a public Bitcoin holder.",
        "Deep capital-market access and multiple funding channels.",
        "High transparency around holdings and treasury execution.",
      ],
      risks: [
        "Single-asset concentration and high sensitivity to Bitcoin drawdowns.",
        "Complex capital stack with recurring senior claims.",
        "Key-person and narrative dependence remain material.",
      ],
      improvements: [
        "Reduce capital-stack complexity over time.",
        "Broaden governance disclosure around treasury stress scenarios.",
      ],
    },
  },
  {
    slug: "digitalx",
    name: "DigitalX",
    ticker: "DCC",
    exchange: "ASX",
    country: "Australia",
    asset: "Multi-Asset",
    assetLabel: "BTC / Multi-Asset",
    holdings: "Prototype basket",
    treasuryNav: "$37.5M",
    treasuryNavValue: 0.0375,
    marketCap: "$52.0M",
    marketCapValue: 0.052,
    mnav: "1.39x",
    model: "Operating company with digital asset treasury",
    dataNote: "Prototype numerical fields where verified live data was not supplied.",
    rating: {
      status: "rated",
      score: 82,
      grade: "A-",
      confidence: 4,
      lastReviewed: "16 Jul 2026",
      categories: categories([9, 8, 8, 9, 16, 12, 12, 8]),
      operatingBusinessSubcategories: [
        { label: "Profitability & Cash Generation", score: 2, max: 3 },
        { label: "Strategic Fit", score: 3, max: 3 },
        { label: "Business Diversification", score: 2, max: 2 },
        { label: "Operating Track Record", score: 2, max: 2 },
      ],
      analystSummary:
        "DigitalX combines an established digital-asset operating business with conservative capital management and strong strategic fit. Its smaller treasury limits scale, but diversified operations and multi-cycle experience improve resilience relative to more leveraged treasury vehicles.",
      treasuryModel: "Digital asset operating company with treasury allocation",
      strengths: [
        "Strong strategic fit between operations and treasury assets.",
        "Conservative capital posture relative to more leveraged vehicles.",
        "Multi-cycle operating experience in digital assets.",
      ],
      risks: [
        "Smaller treasury scale limits market visibility.",
        "Liquidity and analyst coverage remain more limited than mega-cap peers.",
      ],
      improvements: [
        "Expand treasury reporting granularity.",
        "Demonstrate repeatable operating cash generation across cycles.",
      ],
    },
  },
  {
    slug: "metaplanet",
    name: "Metaplanet",
    ticker: "3350",
    exchange: "Tokyo",
    country: "Japan",
    asset: "Bitcoin",
    assetLabel: "BTC",
    holdings: "43,000 BTC",
    treasuryNav: "$2.79B",
    treasuryNavValue: 2.79,
    marketCap: "$5.42B",
    marketCapValue: 5.42,
    mnav: "1.94x",
    model: "Asia-focused Bitcoin treasury company",
    dataNote: "Prototype numerical fields where verified live data was not supplied.",
    rating: {
      status: "rated",
      score: 79,
      grade: "B+",
      confidence: 5,
      lastReviewed: "16 Jul 2026",
      categories: categories([10, 9, 10, 4, 14, 11, 13, 8]),
      operatingBusinessSubcategories: [
        { label: "Profitability & Cash Generation", score: 1, max: 3 },
        { label: "Strategic Fit", score: 1, max: 3 },
        { label: "Business Diversification", score: 1, max: 2 },
        { label: "Operating Track Record", score: 1, max: 2 },
      ],
      analystSummary:
        "Metaplanet has rapidly established itself as Asia’s leading Bitcoin Treasury Company through exceptional capital-market execution, innovative financing, and one of the clearest treasury philosophies in the sector.",
      treasuryModel: "Bitcoin Treasury",
      strengths: [
        "BTC Yield KPI.",
        "Active capital-market execution.",
        "Equity-financing innovation.",
        "Strong investor communication.",
      ],
      risks: [
        "Liquidity remains heavily tied to Bitcoin market conditions.",
        "Continued capital-market access remains important.",
        "The legacy operating business contributes relatively little compared with the Bitcoin treasury.",
      ],
      improvements: [
        "More detailed treasury-risk metrics.",
        "Explicit leverage targets.",
        "Published concentration limits.",
        "Formal treasury-governance framework.",
      ],
    },
  },
  {
    slug: "gumi",
    name: "gumi Inc.",
    ticker: "3903",
    exchange: "Tokyo",
    country: "Japan",
    asset: "XRP",
    assetLabel: "XRP",
    holdings: "Prototype XRP reserve",
    treasuryNav: "$96.0M",
    treasuryNavValue: 0.096,
    marketCap: "$238.0M",
    marketCapValue: 0.238,
    mnav: "2.48x",
    model: "Blockchain operating company with active XRP treasury",
    dataNote: "Prototype numerical fields where verified live data was not supplied.",
    rating: {
      status: "rated",
      score: 76,
      grade: "B+",
      confidence: 4,
      lastReviewed: "16 Jul 2026",
      categories: categories([8, 8, 7, 9, 13, 11, 12, 8]),
      operatingBusinessSubcategories: [
        { label: "Profitability & Cash Generation", score: 2, max: 3 },
        { label: "Strategic Fit", score: 3, max: 3 },
        { label: "Business Diversification", score: 2, max: 2 },
        { label: "Operating Track Record", score: 2, max: 2 },
      ],
      analystSummary:
        "gumi presents one of Japan’s most strategically coherent digital asset treasury models by integrating XRP into an established blockchain and gaming ecosystem rather than treating it as a standalone speculative reserve asset.",
      treasuryModel: "XRP Treasury",
      strengths: [
        "Strategic partnership with SBI.",
        "Public treasury disclosures.",
        "Active treasury oversight.",
        "Innovative covered-call strategy.",
      ],
      risks: [
        "Treasury execution remains in its early stages.",
        "The company remains exposed to digital-asset volatility, particularly through XRP.",
        "Long-term effectiveness has yet to be demonstrated across a full market cycle.",
      ],
      improvements: [
        "Formal treasury-allocation policies.",
        "Concentration limits.",
        "Published treasury-risk metrics.",
        "Treasury-specific KPIs.",
      ],
    },
  },
  {
    slug: "bitmine-immersion",
    name: "BitMine Immersion Technologies",
    ticker: "BMNR",
    exchange: "NYSE American",
    country: "United States",
    asset: "Ethereum",
    assetLabel: "ETH",
    holdings: "Prototype ETH treasury",
    treasuryNav: "$1.35B",
    treasuryNavValue: 1.35,
    marketCap: "$1.92B",
    marketCapValue: 1.92,
    mnav: "1.42x",
    model: "Ethereum treasury and mining infrastructure",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "sharplink-gaming",
    name: "SharpLink Gaming",
    ticker: "SBET",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Ethereum",
    assetLabel: "ETH",
    holdings: "Prototype ETH treasury",
    treasuryNav: "$2.10B",
    treasuryNavValue: 2.1,
    marketCap: "$2.34B",
    marketCapValue: 2.34,
    mnav: "1.11x",
    model: "Ethereum treasury vehicle",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "sol-strategies",
    name: "Sol Strategies",
    ticker: "HODL",
    exchange: "CSE",
    country: "Canada",
    asset: "Solana",
    assetLabel: "SOL",
    holdings: "Prototype SOL reserve",
    treasuryNav: "$178.0M",
    treasuryNavValue: 0.178,
    marketCap: "$242.0M",
    marketCapValue: 0.242,
    mnav: "1.36x",
    model: "Solana treasury and validator exposure",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "defi-development",
    name: "DeFi Development Corp.",
    ticker: "DFDV",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Solana",
    assetLabel: "SOL",
    holdings: "Prototype SOL treasury",
    treasuryNav: "$620.0M",
    treasuryNavValue: 0.62,
    marketCap: "$855.0M",
    marketCapValue: 0.855,
    mnav: "1.38x",
    model: "Solana accumulation and ecosystem exposure",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "bitcoin-group",
    name: "Bitcoin Group SE",
    ticker: "ADE",
    exchange: "Xetra",
    country: "Germany",
    asset: "Bitcoin",
    assetLabel: "BTC",
    holdings: "Prototype BTC treasury",
    treasuryNav: "$218.0M",
    treasuryNavValue: 0.218,
    marketCap: "$310.0M",
    marketCapValue: 0.31,
    mnav: "1.42x",
    model: "Operating company with Bitcoin balance sheet",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "semler-scientific",
    name: "Semler Scientific",
    ticker: "SMLR",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Bitcoin",
    assetLabel: "BTC",
    holdings: "Prototype BTC reserve",
    treasuryNav: "$402.0M",
    treasuryNavValue: 0.402,
    marketCap: "$685.0M",
    marketCapValue: 0.685,
    mnav: "1.70x",
    model: "Healthcare operating company with Bitcoin treasury",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "u-turn",
    name: "Upexi",
    ticker: "UPXI",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Solana",
    assetLabel: "SOL",
    holdings: "Prototype SOL reserve",
    treasuryNav: "$312.0M",
    treasuryNavValue: 0.312,
    marketCap: "$421.0M",
    marketCapValue: 0.421,
    mnav: "1.35x",
    model: "Solana treasury strategy",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "worksport",
    name: "Worksport",
    ticker: "WKSP",
    exchange: "NASDAQ",
    country: "United States",
    asset: "Multi-Asset",
    assetLabel: "BTC / XRP",
    holdings: "Prototype dual-asset reserve",
    treasuryNav: "$14.2M",
    treasuryNavValue: 0.0142,
    marketCap: "$38.0M",
    marketCapValue: 0.038,
    mnav: "2.68x",
    model: "Operating company with dual-asset reserve",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "meitu",
    name: "Meitu",
    ticker: "1357",
    exchange: "HKEX",
    country: "Hong Kong",
    asset: "Multi-Asset",
    assetLabel: "BTC / ETH",
    holdings: "Prototype historical basket",
    treasuryNav: "$156.0M",
    treasuryNavValue: 0.156,
    marketCap: "$1.46B",
    marketCapValue: 1.46,
    mnav: "9.36x",
    model: "Consumer internet company with digital asset allocation",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
  {
    slug: "hyperscale-data",
    name: "Hyperscale Data",
    ticker: "GPUS",
    exchange: "NYSE American",
    country: "United States",
    asset: "XRP",
    assetLabel: "XRP",
    holdings: "Prototype XRP reserve",
    treasuryNav: "$41.0M",
    treasuryNavValue: 0.041,
    marketCap: "$67.0M",
    marketCapValue: 0.067,
    mnav: "1.63x",
    model: "Infrastructure company with XRP treasury allocation",
    rating: { status: "pending" },
    dataNote: "Prototype pending record; no completed DATX rating.",
  },
];


export const metadata: Metadata = {
  title,
  description,
  alternates: {
    canonical: url,
  },
  openGraph: {
    title,
    description,
    url,
    siteName: "DATX",
    type: "website",
    images: [
      {
        url: "https://datxstrategy.com/brand/datx-logo-white.png",
        alt: "DATX",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: ["https://datxstrategy.com/brand/datx-logo-white.png"],
  },
};

export default function TrackerPage() {
  return (
    <Suspense
      fallback={
        <main className="min-h-screen bg-datx-black text-slate-100">
          <div className="container-frame py-14">Loading DATX tracker...</div>
        </main>
      }
    >
      <DatTrackerPrototype basePath="/tracker" companies={companies} publicMode />
    </Suspense>
  );
}
